config/routes.rb
Jsblogger::Application.routes.draw do

  resources :articles
  

end

app/models/article.rb
class Article < ActiveRecord::Base
	validates_presence_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show 
		@article = Article.find(params[:id])
	end

	def new 
		@article = Article.new
	end

	def create
		@article = Article.new(params[:article])
		if @article.save
			flash[:message] = "Article Created"
			redirect_to article_path(@article)
		else
			#Show them the form again
			#with the data, so you're not a jerk
			flash[:message] = "Sorry, there are errors in the form"
			render :new	
		end
	end

	def destroy
		#find the article
		article = Article.destroy(params[:id])
		flash[:message] = "Article '#{article.title} was deleted'"
		#send them back to the index
		redirect_to articles_path

	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		if @article.update_attributes(params[:article])
			flash[:message] = "Article Updated"
			redirect_to article_path(@article)
		else
			flash[:message] = "Sorry, there were errors in the form"
			render :edit
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %> 

app/views/articles/edit.html.erb
<h1>Edit the Article</h1>

<%= render :partial => "form" %>

app/views/articles/index.html.erb
<h1>Hello World</h1>
<ul>
<% @articles.each do |article| %>
	<li><%= link_to article.title, article_path(article) %></li>
<% end %>
</ul>

<%= link_to "New Article", new_article_path, :class=> "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render  :partial => "form" %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<%= link_to "<< Back to Articles List", articles_path %>
<%= link_to "Delete This Article", article_path, :method => :delete, :confirm => "Delete '#{@article.title}'?" %>

<%= link_to "Edit", edit_article_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jsblogger</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="flash"><%= flash[:message] %></p>

<%= yield %>

</body>
</html>